[package]
name = "example"
version.workspace = true
edition.workspace = true

[dependencies]
# config = { workspace = true, features = ["json"] }
config = { workspace = true, features = ["toml"] }
serde = { version = "1", features = ["derive"] }

[lints.clippy]
pedantic = "warn"
nursery = "warn"
