[workspace]
resolver = "2"
members = ["config", "derive", "example"]

[workspace.package]
version = "0.0.0"
edition = "2021"

[workspace.dependencies]
config = { path = "./config" }
derive = { path = "./derive" }
dirs = "5"
eyre = "0.6"
proc-macro2 = "1"
quote = "1"
serde = "1"
syn = "2"
toml = "0.8"
