[package]
name = "derive"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = "2"

[features]
default = []
json = []
toml = []

[lints.clippy]
pedantic = "warn"
nursery = "warn"
