[package]
name = "config"
version.workspace = true
edition.workspace = true

[dependencies]
derive.workspace = true
dirs.workspace = true
eyre.workspace = true
toml.workspace = true

[lints.clippy]
pedantic = "warn"
nursery = "warn"
